/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdvisorChatRouteImport } from './routes/api/advisor-chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorChatRoute = ApiAdvisorChatRouteImport.update({
  id: '/api/advisor-chat',
  path: '/api/advisor-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/advisor-chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/advisor-chat'
  id: '__root__' | '/' | '/api/advisor-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdvisorChatRoute: typeof ApiAdvisorChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor-chat': {
      id: '/api/advisor-chat'
      path: '/api/advisor-chat'
      fullPath: '/api/advisor-chat'
      preLoaderRoute: typeof ApiAdvisorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdvisorChatRoute: ApiAdvisorChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
