/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSaveChatLeadRouteImport } from './routes/api/save-chat-lead'
import { Route as ApiAdvisorChatRouteImport } from './routes/api/advisor-chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveChatLeadRoute = ApiSaveChatLeadRouteImport.update({
  id: '/api/save-chat-lead',
  path: '/api/save-chat-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorChatRoute = ApiAdvisorChatRouteImport.update({
  id: '/api/advisor-chat',
  path: '/api/advisor-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
  '/api/save-chat-lead': typeof ApiSaveChatLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
  '/api/save-chat-lead': typeof ApiSaveChatLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
  '/api/save-chat-lead': typeof ApiSaveChatLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/advisor-chat' | '/api/save-chat-lead'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/advisor-chat' | '/api/save-chat-lead'
  id: '__root__' | '/' | '/api/advisor-chat' | '/api/save-chat-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdvisorChatRoute: typeof ApiAdvisorChatRoute
  ApiSaveChatLeadRoute: typeof ApiSaveChatLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-chat-lead': {
      id: '/api/save-chat-lead'
      path: '/api/save-chat-lead'
      fullPath: '/api/save-chat-lead'
      preLoaderRoute: typeof ApiSaveChatLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor-chat': {
      id: '/api/advisor-chat'
      path: '/api/advisor-chat'
      fullPath: '/api/advisor-chat'
      preLoaderRoute: typeof ApiAdvisorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdvisorChatRoute: ApiAdvisorChatRoute,
  ApiSaveChatLeadRoute: ApiSaveChatLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
