/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TratamientoDatosRouteImport } from './routes/tratamiento-datos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucionesIndexRouteImport } from './routes/soluciones/index'
import { Route as SistemasIndexRouteImport } from './routes/sistemas/index'
import { Route as SectoresIndexRouteImport } from './routes/sectores/index'
import { Route as RecursosIndexRouteImport } from './routes/recursos/index'
import { Route as NosotrosIndexRouteImport } from './routes/nosotros/index'
import { Route as CasosIndexRouteImport } from './routes/casos/index'
import { Route as SolucionesOperacionRouteImport } from './routes/soluciones/operacion'
import { Route as SolucionesEcommerceRentableRouteImport } from './routes/soluciones/ecommerce-rentable'
import { Route as SolucionesCaptacionYCierreRouteImport } from './routes/soluciones/captacion-y-cierre'
import { Route as SistemasSalesFlowRouteImport } from './routes/sistemas/sales-flow'
import { Route as SistemasRevenueEngineRouteImport } from './routes/sistemas/revenue-engine'
import { Route as SistemasRevenueDiagnosticRouteImport } from './routes/sistemas/revenue-diagnostic'
import { Route as SistemasOperationsSystemRouteImport } from './routes/sistemas/operations-system'
import { Route as SistemasDemandSystemRouteImport } from './routes/sistemas/demand-system'
import { Route as SectoresServiciosB2bRouteImport } from './routes/sectores/servicios-b2b'
import { Route as SectoresSaludEsteticaOdontologiaRouteImport } from './routes/sectores/salud-estetica-odontologia'
import { Route as SectoresIndustriaDistribucionRouteImport } from './routes/sectores/industria-distribucion'
import { Route as SectoresEducacionRouteImport } from './routes/sectores/educacion'
import { Route as SectoresEcommerceRouteImport } from './routes/sectores/ecommerce'
import { Route as SectoresConstruccionInmobiliarioRouteImport } from './routes/sectores/construccion-inmobiliario'
import { Route as OpsLoginRouteImport } from './routes/ops/login'
import { Route as OpsAiControlRouteImport } from './routes/ops/ai-control'
import { Route as NosotrosTrabajaConNosotrosRouteImport } from './routes/nosotros/trabaja-con-nosotros'
import { Route as NosotrosComoTrabajamosRouteImport } from './routes/nosotros/como-trabajamos'
import { Route as ApiSaveChatLeadRouteImport } from './routes/api/save-chat-lead'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiAdvisorChatRouteImport } from './routes/api/advisor-chat'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminDebugVerifyRouteImport } from './routes/api/admin/debug-verify'
import { Route as ApiAdminDebugRouteImport } from './routes/api/admin/debug'
import { Route as ApiAdminAiUsageRouteImport } from './routes/api/admin/ai/usage'
import { Route as ApiAdminAiTestProviderRouteImport } from './routes/api/admin/ai/test-provider'
import { Route as ApiAdminAiModelsRouteImport } from './routes/api/admin/ai/models'
import { Route as ApiAdminAiConfigRouteImport } from './routes/api/admin/ai/config'

const TratamientoDatosRoute = TratamientoDatosRouteImport.update({
  id: '/tratamiento-datos',
  path: '/tratamiento-datos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesIndexRoute = SolucionesIndexRouteImport.update({
  id: '/soluciones/',
  path: '/soluciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasIndexRoute = SistemasIndexRouteImport.update({
  id: '/sistemas/',
  path: '/sistemas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresIndexRoute = SectoresIndexRouteImport.update({
  id: '/sectores/',
  path: '/sectores/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosIndexRoute = RecursosIndexRouteImport.update({
  id: '/recursos/',
  path: '/recursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosIndexRoute = NosotrosIndexRouteImport.update({
  id: '/nosotros/',
  path: '/nosotros/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosIndexRoute = CasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesOperacionRoute = SolucionesOperacionRouteImport.update({
  id: '/soluciones/operacion',
  path: '/soluciones/operacion',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesEcommerceRentableRoute =
  SolucionesEcommerceRentableRouteImport.update({
    id: '/soluciones/ecommerce-rentable',
    path: '/soluciones/ecommerce-rentable',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucionesCaptacionYCierreRoute =
  SolucionesCaptacionYCierreRouteImport.update({
    id: '/soluciones/captacion-y-cierre',
    path: '/soluciones/captacion-y-cierre',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemasSalesFlowRoute = SistemasSalesFlowRouteImport.update({
  id: '/sistemas/sales-flow',
  path: '/sistemas/sales-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasRevenueEngineRoute = SistemasRevenueEngineRouteImport.update({
  id: '/sistemas/revenue-engine',
  path: '/sistemas/revenue-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasRevenueDiagnosticRoute =
  SistemasRevenueDiagnosticRouteImport.update({
    id: '/sistemas/revenue-diagnostic',
    path: '/sistemas/revenue-diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemasOperationsSystemRoute =
  SistemasOperationsSystemRouteImport.update({
    id: '/sistemas/operations-system',
    path: '/sistemas/operations-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemasDemandSystemRoute = SistemasDemandSystemRouteImport.update({
  id: '/sistemas/demand-system',
  path: '/sistemas/demand-system',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresServiciosB2bRoute = SectoresServiciosB2bRouteImport.update({
  id: '/sectores/servicios-b2b',
  path: '/sectores/servicios-b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresSaludEsteticaOdontologiaRoute =
  SectoresSaludEsteticaOdontologiaRouteImport.update({
    id: '/sectores/salud-estetica-odontologia',
    path: '/sectores/salud-estetica-odontologia',
    getParentRoute: () => rootRouteImport,
  } as any)
const SectoresIndustriaDistribucionRoute =
  SectoresIndustriaDistribucionRouteImport.update({
    id: '/sectores/industria-distribucion',
    path: '/sectores/industria-distribucion',
    getParentRoute: () => rootRouteImport,
  } as any)
const SectoresEducacionRoute = SectoresEducacionRouteImport.update({
  id: '/sectores/educacion',
  path: '/sectores/educacion',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresEcommerceRoute = SectoresEcommerceRouteImport.update({
  id: '/sectores/ecommerce',
  path: '/sectores/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresConstruccionInmobiliarioRoute =
  SectoresConstruccionInmobiliarioRouteImport.update({
    id: '/sectores/construccion-inmobiliario',
    path: '/sectores/construccion-inmobiliario',
    getParentRoute: () => rootRouteImport,
  } as any)
const OpsLoginRoute = OpsLoginRouteImport.update({
  id: '/ops/login',
  path: '/ops/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsAiControlRoute = OpsAiControlRouteImport.update({
  id: '/ops/ai-control',
  path: '/ops/ai-control',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosTrabajaConNosotrosRoute =
  NosotrosTrabajaConNosotrosRouteImport.update({
    id: '/nosotros/trabaja-con-nosotros',
    path: '/nosotros/trabaja-con-nosotros',
    getParentRoute: () => rootRouteImport,
  } as any)
const NosotrosComoTrabajamosRoute = NosotrosComoTrabajamosRouteImport.update({
  id: '/nosotros/como-trabajamos',
  path: '/nosotros/como-trabajamos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveChatLeadRoute = ApiSaveChatLeadRouteImport.update({
  id: '/api/save-chat-lead',
  path: '/api/save-chat-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorChatRoute = ApiAdvisorChatRouteImport.update({
  id: '/api/advisor-chat',
  path: '/api/advisor-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDebugVerifyRoute = ApiAdminDebugVerifyRouteImport.update({
  id: '/api/admin/debug-verify',
  path: '/api/admin/debug-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDebugRoute = ApiAdminDebugRouteImport.update({
  id: '/api/admin/debug',
  path: '/api/admin/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiUsageRoute = ApiAdminAiUsageRouteImport.update({
  id: '/api/admin/ai/usage',
  path: '/api/admin/ai/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiTestProviderRoute = ApiAdminAiTestProviderRouteImport.update({
  id: '/api/admin/ai/test-provider',
  path: '/api/admin/ai/test-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiModelsRoute = ApiAdminAiModelsRouteImport.update({
  id: '/api/admin/ai/models',
  path: '/api/admin/ai/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiConfigRoute = ApiAdminAiConfigRouteImport.update({
  id: '/api/admin/ai/config',
  path: '/api/admin/ai/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/tratamiento-datos': typeof TratamientoDatosRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/save-chat-lead': typeof ApiSaveChatLeadRoute
  '/nosotros/como-trabajamos': typeof NosotrosComoTrabajamosRoute
  '/nosotros/trabaja-con-nosotros': typeof NosotrosTrabajaConNosotrosRoute
  '/ops/ai-control': typeof OpsAiControlRoute
  '/ops/login': typeof OpsLoginRoute
  '/sectores/construccion-inmobiliario': typeof SectoresConstruccionInmobiliarioRoute
  '/sectores/ecommerce': typeof SectoresEcommerceRoute
  '/sectores/educacion': typeof SectoresEducacionRoute
  '/sectores/industria-distribucion': typeof SectoresIndustriaDistribucionRoute
  '/sectores/salud-estetica-odontologia': typeof SectoresSaludEsteticaOdontologiaRoute
  '/sectores/servicios-b2b': typeof SectoresServiciosB2bRoute
  '/sistemas/demand-system': typeof SistemasDemandSystemRoute
  '/sistemas/operations-system': typeof SistemasOperationsSystemRoute
  '/sistemas/revenue-diagnostic': typeof SistemasRevenueDiagnosticRoute
  '/sistemas/revenue-engine': typeof SistemasRevenueEngineRoute
  '/sistemas/sales-flow': typeof SistemasSalesFlowRoute
  '/soluciones/captacion-y-cierre': typeof SolucionesCaptacionYCierreRoute
  '/soluciones/ecommerce-rentable': typeof SolucionesEcommerceRentableRoute
  '/soluciones/operacion': typeof SolucionesOperacionRoute
  '/casos/': typeof CasosIndexRoute
  '/nosotros/': typeof NosotrosIndexRoute
  '/recursos/': typeof RecursosIndexRoute
  '/sectores/': typeof SectoresIndexRoute
  '/sistemas/': typeof SistemasIndexRoute
  '/soluciones/': typeof SolucionesIndexRoute
  '/api/admin/debug': typeof ApiAdminDebugRoute
  '/api/admin/debug-verify': typeof ApiAdminDebugVerifyRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/ai/config': typeof ApiAdminAiConfigRoute
  '/api/admin/ai/models': typeof ApiAdminAiModelsRoute
  '/api/admin/ai/test-provider': typeof ApiAdminAiTestProviderRoute
  '/api/admin/ai/usage': typeof ApiAdminAiUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/tratamiento-datos': typeof TratamientoDatosRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/save-chat-lead': typeof ApiSaveChatLeadRoute
  '/nosotros/como-trabajamos': typeof NosotrosComoTrabajamosRoute
  '/nosotros/trabaja-con-nosotros': typeof NosotrosTrabajaConNosotrosRoute
  '/ops/ai-control': typeof OpsAiControlRoute
  '/ops/login': typeof OpsLoginRoute
  '/sectores/construccion-inmobiliario': typeof SectoresConstruccionInmobiliarioRoute
  '/sectores/ecommerce': typeof SectoresEcommerceRoute
  '/sectores/educacion': typeof SectoresEducacionRoute
  '/sectores/industria-distribucion': typeof SectoresIndustriaDistribucionRoute
  '/sectores/salud-estetica-odontologia': typeof SectoresSaludEsteticaOdontologiaRoute
  '/sectores/servicios-b2b': typeof SectoresServiciosB2bRoute
  '/sistemas/demand-system': typeof SistemasDemandSystemRoute
  '/sistemas/operations-system': typeof SistemasOperationsSystemRoute
  '/sistemas/revenue-diagnostic': typeof SistemasRevenueDiagnosticRoute
  '/sistemas/revenue-engine': typeof SistemasRevenueEngineRoute
  '/sistemas/sales-flow': typeof SistemasSalesFlowRoute
  '/soluciones/captacion-y-cierre': typeof SolucionesCaptacionYCierreRoute
  '/soluciones/ecommerce-rentable': typeof SolucionesEcommerceRentableRoute
  '/soluciones/operacion': typeof SolucionesOperacionRoute
  '/casos': typeof CasosIndexRoute
  '/nosotros': typeof NosotrosIndexRoute
  '/recursos': typeof RecursosIndexRoute
  '/sectores': typeof SectoresIndexRoute
  '/sistemas': typeof SistemasIndexRoute
  '/soluciones': typeof SolucionesIndexRoute
  '/api/admin/debug': typeof ApiAdminDebugRoute
  '/api/admin/debug-verify': typeof ApiAdminDebugVerifyRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/ai/config': typeof ApiAdminAiConfigRoute
  '/api/admin/ai/models': typeof ApiAdminAiModelsRoute
  '/api/admin/ai/test-provider': typeof ApiAdminAiTestProviderRoute
  '/api/admin/ai/usage': typeof ApiAdminAiUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/tratamiento-datos': typeof TratamientoDatosRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/save-chat-lead': typeof ApiSaveChatLeadRoute
  '/nosotros/como-trabajamos': typeof NosotrosComoTrabajamosRoute
  '/nosotros/trabaja-con-nosotros': typeof NosotrosTrabajaConNosotrosRoute
  '/ops/ai-control': typeof OpsAiControlRoute
  '/ops/login': typeof OpsLoginRoute
  '/sectores/construccion-inmobiliario': typeof SectoresConstruccionInmobiliarioRoute
  '/sectores/ecommerce': typeof SectoresEcommerceRoute
  '/sectores/educacion': typeof SectoresEducacionRoute
  '/sectores/industria-distribucion': typeof SectoresIndustriaDistribucionRoute
  '/sectores/salud-estetica-odontologia': typeof SectoresSaludEsteticaOdontologiaRoute
  '/sectores/servicios-b2b': typeof SectoresServiciosB2bRoute
  '/sistemas/demand-system': typeof SistemasDemandSystemRoute
  '/sistemas/operations-system': typeof SistemasOperationsSystemRoute
  '/sistemas/revenue-diagnostic': typeof SistemasRevenueDiagnosticRoute
  '/sistemas/revenue-engine': typeof SistemasRevenueEngineRoute
  '/sistemas/sales-flow': typeof SistemasSalesFlowRoute
  '/soluciones/captacion-y-cierre': typeof SolucionesCaptacionYCierreRoute
  '/soluciones/ecommerce-rentable': typeof SolucionesEcommerceRentableRoute
  '/soluciones/operacion': typeof SolucionesOperacionRoute
  '/casos/': typeof CasosIndexRoute
  '/nosotros/': typeof NosotrosIndexRoute
  '/recursos/': typeof RecursosIndexRoute
  '/sectores/': typeof SectoresIndexRoute
  '/sistemas/': typeof SistemasIndexRoute
  '/soluciones/': typeof SolucionesIndexRoute
  '/api/admin/debug': typeof ApiAdminDebugRoute
  '/api/admin/debug-verify': typeof ApiAdminDebugVerifyRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/ai/config': typeof ApiAdminAiConfigRoute
  '/api/admin/ai/models': typeof ApiAdminAiModelsRoute
  '/api/admin/ai/test-provider': typeof ApiAdminAiTestProviderRoute
  '/api/admin/ai/usage': typeof ApiAdminAiUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/privacidad'
    | '/tratamiento-datos'
    | '/api/advisor-chat'
    | '/api/leads'
    | '/api/save-chat-lead'
    | '/nosotros/como-trabajamos'
    | '/nosotros/trabaja-con-nosotros'
    | '/ops/ai-control'
    | '/ops/login'
    | '/sectores/construccion-inmobiliario'
    | '/sectores/ecommerce'
    | '/sectores/educacion'
    | '/sectores/industria-distribucion'
    | '/sectores/salud-estetica-odontologia'
    | '/sectores/servicios-b2b'
    | '/sistemas/demand-system'
    | '/sistemas/operations-system'
    | '/sistemas/revenue-diagnostic'
    | '/sistemas/revenue-engine'
    | '/sistemas/sales-flow'
    | '/soluciones/captacion-y-cierre'
    | '/soluciones/ecommerce-rentable'
    | '/soluciones/operacion'
    | '/casos/'
    | '/nosotros/'
    | '/recursos/'
    | '/sectores/'
    | '/sistemas/'
    | '/soluciones/'
    | '/api/admin/debug'
    | '/api/admin/debug-verify'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/ai/config'
    | '/api/admin/ai/models'
    | '/api/admin/ai/test-provider'
    | '/api/admin/ai/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/privacidad'
    | '/tratamiento-datos'
    | '/api/advisor-chat'
    | '/api/leads'
    | '/api/save-chat-lead'
    | '/nosotros/como-trabajamos'
    | '/nosotros/trabaja-con-nosotros'
    | '/ops/ai-control'
    | '/ops/login'
    | '/sectores/construccion-inmobiliario'
    | '/sectores/ecommerce'
    | '/sectores/educacion'
    | '/sectores/industria-distribucion'
    | '/sectores/salud-estetica-odontologia'
    | '/sectores/servicios-b2b'
    | '/sistemas/demand-system'
    | '/sistemas/operations-system'
    | '/sistemas/revenue-diagnostic'
    | '/sistemas/revenue-engine'
    | '/sistemas/sales-flow'
    | '/soluciones/captacion-y-cierre'
    | '/soluciones/ecommerce-rentable'
    | '/soluciones/operacion'
    | '/casos'
    | '/nosotros'
    | '/recursos'
    | '/sectores'
    | '/sistemas'
    | '/soluciones'
    | '/api/admin/debug'
    | '/api/admin/debug-verify'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/ai/config'
    | '/api/admin/ai/models'
    | '/api/admin/ai/test-provider'
    | '/api/admin/ai/usage'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/privacidad'
    | '/tratamiento-datos'
    | '/api/advisor-chat'
    | '/api/leads'
    | '/api/save-chat-lead'
    | '/nosotros/como-trabajamos'
    | '/nosotros/trabaja-con-nosotros'
    | '/ops/ai-control'
    | '/ops/login'
    | '/sectores/construccion-inmobiliario'
    | '/sectores/ecommerce'
    | '/sectores/educacion'
    | '/sectores/industria-distribucion'
    | '/sectores/salud-estetica-odontologia'
    | '/sectores/servicios-b2b'
    | '/sistemas/demand-system'
    | '/sistemas/operations-system'
    | '/sistemas/revenue-diagnostic'
    | '/sistemas/revenue-engine'
    | '/sistemas/sales-flow'
    | '/soluciones/captacion-y-cierre'
    | '/soluciones/ecommerce-rentable'
    | '/soluciones/operacion'
    | '/casos/'
    | '/nosotros/'
    | '/recursos/'
    | '/sectores/'
    | '/sistemas/'
    | '/soluciones/'
    | '/api/admin/debug'
    | '/api/admin/debug-verify'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/ai/config'
    | '/api/admin/ai/models'
    | '/api/admin/ai/test-provider'
    | '/api/admin/ai/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  CookiesRoute: typeof CookiesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TratamientoDatosRoute: typeof TratamientoDatosRoute
  ApiAdvisorChatRoute: typeof ApiAdvisorChatRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiSaveChatLeadRoute: typeof ApiSaveChatLeadRoute
  NosotrosComoTrabajamosRoute: typeof NosotrosComoTrabajamosRoute
  NosotrosTrabajaConNosotrosRoute: typeof NosotrosTrabajaConNosotrosRoute
  OpsAiControlRoute: typeof OpsAiControlRoute
  OpsLoginRoute: typeof OpsLoginRoute
  SectoresConstruccionInmobiliarioRoute: typeof SectoresConstruccionInmobiliarioRoute
  SectoresEcommerceRoute: typeof SectoresEcommerceRoute
  SectoresEducacionRoute: typeof SectoresEducacionRoute
  SectoresIndustriaDistribucionRoute: typeof SectoresIndustriaDistribucionRoute
  SectoresSaludEsteticaOdontologiaRoute: typeof SectoresSaludEsteticaOdontologiaRoute
  SectoresServiciosB2bRoute: typeof SectoresServiciosB2bRoute
  SistemasDemandSystemRoute: typeof SistemasDemandSystemRoute
  SistemasOperationsSystemRoute: typeof SistemasOperationsSystemRoute
  SistemasRevenueDiagnosticRoute: typeof SistemasRevenueDiagnosticRoute
  SistemasRevenueEngineRoute: typeof SistemasRevenueEngineRoute
  SistemasSalesFlowRoute: typeof SistemasSalesFlowRoute
  SolucionesCaptacionYCierreRoute: typeof SolucionesCaptacionYCierreRoute
  SolucionesEcommerceRentableRoute: typeof SolucionesEcommerceRentableRoute
  SolucionesOperacionRoute: typeof SolucionesOperacionRoute
  CasosIndexRoute: typeof CasosIndexRoute
  NosotrosIndexRoute: typeof NosotrosIndexRoute
  RecursosIndexRoute: typeof RecursosIndexRoute
  SectoresIndexRoute: typeof SectoresIndexRoute
  SistemasIndexRoute: typeof SistemasIndexRoute
  SolucionesIndexRoute: typeof SolucionesIndexRoute
  ApiAdminDebugRoute: typeof ApiAdminDebugRoute
  ApiAdminDebugVerifyRoute: typeof ApiAdminDebugVerifyRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminAiConfigRoute: typeof ApiAdminAiConfigRoute
  ApiAdminAiModelsRoute: typeof ApiAdminAiModelsRoute
  ApiAdminAiTestProviderRoute: typeof ApiAdminAiTestProviderRoute
  ApiAdminAiUsageRoute: typeof ApiAdminAiUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tratamiento-datos': {
      id: '/tratamiento-datos'
      path: '/tratamiento-datos'
      fullPath: '/tratamiento-datos'
      preLoaderRoute: typeof TratamientoDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones/': {
      id: '/soluciones/'
      path: '/soluciones'
      fullPath: '/soluciones/'
      preLoaderRoute: typeof SolucionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/': {
      id: '/sistemas/'
      path: '/sistemas'
      fullPath: '/sistemas/'
      preLoaderRoute: typeof SistemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/': {
      id: '/sectores/'
      path: '/sectores'
      fullPath: '/sectores/'
      preLoaderRoute: typeof SectoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/': {
      id: '/recursos/'
      path: '/recursos'
      fullPath: '/recursos/'
      preLoaderRoute: typeof RecursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros/': {
      id: '/nosotros/'
      path: '/nosotros'
      fullPath: '/nosotros/'
      preLoaderRoute: typeof NosotrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/': {
      id: '/casos/'
      path: '/casos'
      fullPath: '/casos/'
      preLoaderRoute: typeof CasosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones/operacion': {
      id: '/soluciones/operacion'
      path: '/soluciones/operacion'
      fullPath: '/soluciones/operacion'
      preLoaderRoute: typeof SolucionesOperacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones/ecommerce-rentable': {
      id: '/soluciones/ecommerce-rentable'
      path: '/soluciones/ecommerce-rentable'
      fullPath: '/soluciones/ecommerce-rentable'
      preLoaderRoute: typeof SolucionesEcommerceRentableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones/captacion-y-cierre': {
      id: '/soluciones/captacion-y-cierre'
      path: '/soluciones/captacion-y-cierre'
      fullPath: '/soluciones/captacion-y-cierre'
      preLoaderRoute: typeof SolucionesCaptacionYCierreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/sales-flow': {
      id: '/sistemas/sales-flow'
      path: '/sistemas/sales-flow'
      fullPath: '/sistemas/sales-flow'
      preLoaderRoute: typeof SistemasSalesFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/revenue-engine': {
      id: '/sistemas/revenue-engine'
      path: '/sistemas/revenue-engine'
      fullPath: '/sistemas/revenue-engine'
      preLoaderRoute: typeof SistemasRevenueEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/revenue-diagnostic': {
      id: '/sistemas/revenue-diagnostic'
      path: '/sistemas/revenue-diagnostic'
      fullPath: '/sistemas/revenue-diagnostic'
      preLoaderRoute: typeof SistemasRevenueDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/operations-system': {
      id: '/sistemas/operations-system'
      path: '/sistemas/operations-system'
      fullPath: '/sistemas/operations-system'
      preLoaderRoute: typeof SistemasOperationsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/demand-system': {
      id: '/sistemas/demand-system'
      path: '/sistemas/demand-system'
      fullPath: '/sistemas/demand-system'
      preLoaderRoute: typeof SistemasDemandSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/servicios-b2b': {
      id: '/sectores/servicios-b2b'
      path: '/sectores/servicios-b2b'
      fullPath: '/sectores/servicios-b2b'
      preLoaderRoute: typeof SectoresServiciosB2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/salud-estetica-odontologia': {
      id: '/sectores/salud-estetica-odontologia'
      path: '/sectores/salud-estetica-odontologia'
      fullPath: '/sectores/salud-estetica-odontologia'
      preLoaderRoute: typeof SectoresSaludEsteticaOdontologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/industria-distribucion': {
      id: '/sectores/industria-distribucion'
      path: '/sectores/industria-distribucion'
      fullPath: '/sectores/industria-distribucion'
      preLoaderRoute: typeof SectoresIndustriaDistribucionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/educacion': {
      id: '/sectores/educacion'
      path: '/sectores/educacion'
      fullPath: '/sectores/educacion'
      preLoaderRoute: typeof SectoresEducacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/ecommerce': {
      id: '/sectores/ecommerce'
      path: '/sectores/ecommerce'
      fullPath: '/sectores/ecommerce'
      preLoaderRoute: typeof SectoresEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/construccion-inmobiliario': {
      id: '/sectores/construccion-inmobiliario'
      path: '/sectores/construccion-inmobiliario'
      fullPath: '/sectores/construccion-inmobiliario'
      preLoaderRoute: typeof SectoresConstruccionInmobiliarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/login': {
      id: '/ops/login'
      path: '/ops/login'
      fullPath: '/ops/login'
      preLoaderRoute: typeof OpsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/ai-control': {
      id: '/ops/ai-control'
      path: '/ops/ai-control'
      fullPath: '/ops/ai-control'
      preLoaderRoute: typeof OpsAiControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros/trabaja-con-nosotros': {
      id: '/nosotros/trabaja-con-nosotros'
      path: '/nosotros/trabaja-con-nosotros'
      fullPath: '/nosotros/trabaja-con-nosotros'
      preLoaderRoute: typeof NosotrosTrabajaConNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros/como-trabajamos': {
      id: '/nosotros/como-trabajamos'
      path: '/nosotros/como-trabajamos'
      fullPath: '/nosotros/como-trabajamos'
      preLoaderRoute: typeof NosotrosComoTrabajamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-chat-lead': {
      id: '/api/save-chat-lead'
      path: '/api/save-chat-lead'
      fullPath: '/api/save-chat-lead'
      preLoaderRoute: typeof ApiSaveChatLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor-chat': {
      id: '/api/advisor-chat'
      path: '/api/advisor-chat'
      fullPath: '/api/advisor-chat'
      preLoaderRoute: typeof ApiAdvisorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/debug-verify': {
      id: '/api/admin/debug-verify'
      path: '/api/admin/debug-verify'
      fullPath: '/api/admin/debug-verify'
      preLoaderRoute: typeof ApiAdminDebugVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/debug': {
      id: '/api/admin/debug'
      path: '/api/admin/debug'
      fullPath: '/api/admin/debug'
      preLoaderRoute: typeof ApiAdminDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai/usage': {
      id: '/api/admin/ai/usage'
      path: '/api/admin/ai/usage'
      fullPath: '/api/admin/ai/usage'
      preLoaderRoute: typeof ApiAdminAiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai/test-provider': {
      id: '/api/admin/ai/test-provider'
      path: '/api/admin/ai/test-provider'
      fullPath: '/api/admin/ai/test-provider'
      preLoaderRoute: typeof ApiAdminAiTestProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai/models': {
      id: '/api/admin/ai/models'
      path: '/api/admin/ai/models'
      fullPath: '/api/admin/ai/models'
      preLoaderRoute: typeof ApiAdminAiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai/config': {
      id: '/api/admin/ai/config'
      path: '/api/admin/ai/config'
      fullPath: '/api/admin/ai/config'
      preLoaderRoute: typeof ApiAdminAiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  CookiesRoute: CookiesRoute,
  PrivacidadRoute: PrivacidadRoute,
  TratamientoDatosRoute: TratamientoDatosRoute,
  ApiAdvisorChatRoute: ApiAdvisorChatRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiSaveChatLeadRoute: ApiSaveChatLeadRoute,
  NosotrosComoTrabajamosRoute: NosotrosComoTrabajamosRoute,
  NosotrosTrabajaConNosotrosRoute: NosotrosTrabajaConNosotrosRoute,
  OpsAiControlRoute: OpsAiControlRoute,
  OpsLoginRoute: OpsLoginRoute,
  SectoresConstruccionInmobiliarioRoute: SectoresConstruccionInmobiliarioRoute,
  SectoresEcommerceRoute: SectoresEcommerceRoute,
  SectoresEducacionRoute: SectoresEducacionRoute,
  SectoresIndustriaDistribucionRoute: SectoresIndustriaDistribucionRoute,
  SectoresSaludEsteticaOdontologiaRoute: SectoresSaludEsteticaOdontologiaRoute,
  SectoresServiciosB2bRoute: SectoresServiciosB2bRoute,
  SistemasDemandSystemRoute: SistemasDemandSystemRoute,
  SistemasOperationsSystemRoute: SistemasOperationsSystemRoute,
  SistemasRevenueDiagnosticRoute: SistemasRevenueDiagnosticRoute,
  SistemasRevenueEngineRoute: SistemasRevenueEngineRoute,
  SistemasSalesFlowRoute: SistemasSalesFlowRoute,
  SolucionesCaptacionYCierreRoute: SolucionesCaptacionYCierreRoute,
  SolucionesEcommerceRentableRoute: SolucionesEcommerceRentableRoute,
  SolucionesOperacionRoute: SolucionesOperacionRoute,
  CasosIndexRoute: CasosIndexRoute,
  NosotrosIndexRoute: NosotrosIndexRoute,
  RecursosIndexRoute: RecursosIndexRoute,
  SectoresIndexRoute: SectoresIndexRoute,
  SistemasIndexRoute: SistemasIndexRoute,
  SolucionesIndexRoute: SolucionesIndexRoute,
  ApiAdminDebugRoute: ApiAdminDebugRoute,
  ApiAdminDebugVerifyRoute: ApiAdminDebugVerifyRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminAiConfigRoute: ApiAdminAiConfigRoute,
  ApiAdminAiModelsRoute: ApiAdminAiModelsRoute,
  ApiAdminAiTestProviderRoute: ApiAdminAiTestProviderRoute,
  ApiAdminAiUsageRoute: ApiAdminAiUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
